### DISCUSSION TITLE
Solar sensor collect total instead of daily consumption

### DISCUSSION THREAD

**Discussion by brunopiras** [ulic75/power-flow-card#104] [Q&A]
Hi,

the four sensor:

```
entities:
  battery:
    consumption: sensor.total_battery_energy_out
    production: sensor.total_battery_energy_in
  grid:
    consumption: sensor.total_enel_consumed
    production: ''
  solar: sensor.total_photovoltaics_energy
```

all working fine except the solar, it is collecting the total of energy production since is creation, same configuration in energy dashboard classic works fine with daily consumption and production.

Thanks
