### DISCUSSION TITLE
Full example, I seem to be missing something

### DISCUSSION THREAD

**Discussion by philipmather** [ulic75/power-flow-card#106] [Q&A]
Could I ask for the fullest possible example to be added to the documentation, I think I must be missing something as I have this config...
```
type: custom:power-flow-card
entities:
  battery:
    consumption: sensor.givtcp_ce2208g084_battery_to_house
    production: sensor.givtcp_ce2208g084_solar_to_battery
  grid:
    consumption: sensor.givtcp_ce2208g084_grid_to_house
    production: sensor.givtcp_ce2208g084_solar_to_grid
  solar:
    consumption: sensor.givtcp_ce2208g084_solar_to_house
    production: sensor.givtcp_ce2208g084_solar_to_grid
  battery_charge: sensor.givtcp_dy2216g450_battery_soc
watt_threshold: 1000
```
...but I don't see anything going from Solar to House? Obviously I've just sort of assumed Solar can be done as a split entity? I also have grid_to_battery (we have cheap times to import power so people charge their batteries overnight and then discharge later, called load shifting).
