### DISCUSSION TITLE
Should I be seeing a dot moving from grid to battery when charging my battery from the grid?

### DISCUSSION THREAD

**Discussion by derekyle** [ulic75/power-flow-card#108] [Q&A]
I don't have solar panels, so I charge my battery from the grid and use it during peak power. Everything seems to be working with this card except there is no dot moving from grid to battery even though the battery shows the correct kW for power coming in or out. Is that simply a limitation of the card or do I have something setup wrong?

**Comment by ulic75** [comment]
Looks like it is probably a bug.  I would expect it to work with the below configuration, but it doesn't in my test environment.
```
type: custom:power-flow-card
title: Realtime Distribution
entities:
  battery: input_number.battery_io
  battery_charge: input_number.battery_pct
  grid: input_number.grid_io
```
