### DISCUSSION TITLE
calculated house consumption sensor?

### DISCUSSION THREAD

**Discussion by seebaer1976** [ulic75/power-flow-card#131] [Q&A]
one question, in which sensor is the calculated house consumption stored?

**Comment by ulic75** [comment]
The Home value is calculated by adding all of the production values together and then subtracting the consumption values if any.

**Reply by seebaer1976** [reply]
wanted to know how the sensor is called, where the results are stored? so that I can use it and then I don't have to create a new one

**Reply by ulic75** [reply]
It doesn't exist.  The value is recalculated every time one of the other entities change and it not store anywhere.

**Reply by Redherring9** [reply]
> The Home value is calculated by adding all of the production values together and then subtracting the consumption values if any.

I was a little confused when I first installed this… this explanation helps - however what I am seeing doesn’t really work.
Now, it might be my configuration.  
My solar is producing approx 6kW… most of which is charging the battery 
From my Sonnen app dashboard I get this 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/34952839/232338876-2dff8e8b-a737-4fbb-afdd-740a75cb1b0e.png">
Which shows ~6kW produced by Solar, ~2kW consumed by the house, ~2kW charging the battery, and ~2kW sent to the grid.

I am guessing it is my entities, since I get something weirder
<img width="530" alt="image" src="https://user-images.githubusercontent.com/34952839/232338956-37201f8d-0306-48e1-8751-96d275e2cf53.png">

**Reply by DoMiNiOuS** [reply]
Looks to me like you need to invert battery and grid maybe as they are the wrong way round which give you the false readings home readings.
inverted_entities: grid, battery

**Reply by ulic75** [reply]
@Redherring9 Can you post your config?  Also, I'd suggest that you temporarily set watt_threshold to like 100000 to ensure everything is displayed in watts so you don't have weird math rounding.  My guess is that some of your sensors are inverted or something.

**Reply by Redherring9** [reply]
THANKS - both.
Made some progress.  I think I have the right entities now.  
the only thing I am unsure about, I am showing the solar sending power to both the battery and the grid, whereas the power is to the battery, and then house + charging (now approx 200W), and then the remaining off to the grid

![image](https://user-images.githubusercontent.com/34952839/232340489-ca27167a-6865-4c36-9ca1-bee9244ad75e.jpeg)


My config is now
```
  type: custom:power-flow-card
  entities:  
    battery:    
      consumption: sensor.sonnenbatterie_nnnnn_consumption_w    
      production: sensor.sonnenbatterie_nnnnn_meter_production_4_1_w_total  
    battery_charge: sensor.sonnenbatterie_nnnnn_state_charge_real  
    grid:    
      consumption: sensor.sonnenbatterie_nnnnn_state_grid_input    
      production: sensor.sonnenbatterie_nnnnn_state_grid_output  
    solar: sensor.solaredge_current_power 
```

**Reply by DoMiNiOuS** [reply]
sensor.sonnenbatterie_70585_meter_production_4_1_w_total
That sensor looks like total and not current wattage?
Do you have one like your consumption
sensor.sonnenbatterie_70585_consumption_w
but instead
sensor.sonnenbatterie_70585_production_w
Possibly?

**Reply by Redherring9** [reply]
When I check the entity it is showing the current product - it seems to be an aggregation versus a cumulative
<img width="551" alt="image" src="https://user-images.githubusercontent.com/34952839/232341442-4a7bcb3b-3abd-436a-88d7-deb8ae148e0e.png">

Which appears to be the Solar Production INTO the battery.
Which still isn’t quite what I think I am after.

whereas consumption_w is a in/out entity
<img width="536" alt="image" src="https://user-images.githubusercontent.com/34952839/232341602-e28e0385-be81-4c6a-8c6c-6f8a396d783c.png">

**Reply by DoMiNiOuS** [reply]
Change to this
    battery: sensor.sonnenbatterie_nnnnn_consumption_w 
Then check charge/discharge is right way round and use the inverted_entities: battery if it isnt

**Reply by Redherring9** [reply]
I appreciate your help.  I am quite sure I am abusing github’s “discussions” forum ;)
however I think I am close.
![image](https://user-images.githubusercontent.com/34952839/232644954-8f57fcae-ab20-41e6-891a-86637c348aef.jpeg)

And shortly after, here are my four attempts :) you can see the first one is pretty close
![image](https://user-images.githubusercontent.com/34952839/232645031-96229bc7-d799-4a7b-afec-a2de622ffd66.jpeg)

here is the config for that one
```
type: custom:power-flow-card
entities:
  battery:
    consumption: sensor.sonnenbatterie_nnnnn_consumption_w
    production: sensor.sonnenbatterie_nnnnn_meter_production_4_1_w_total
  battery_charge: sensor.sonnenbatterie_nnnnn_state_charge_real
  grid:
    consumption: sensor.sonnenbatterie_nnnnn_state_grid_input
    production: sensor.sonnenbatterie_nnnnn_state_grid_output
  solar: sensor.solaredge_current_power
```
