### DISCUSSION TITLE
not an issue :)

### DISCUSSION THREAD

**Discussion by ChristophCaina** [ulic75/power-flow-card#42] [General]
Hi, within your description, you've made the following example config:

```
type: custom:power-flow-card
title: Power Distribution
entities:
  battery: sensor.battery_in_out
  battery_charge: sensor.battery_percent
  grid: sensor.grid_in_out
  solar: sensor.solar_out
max_flow_rate: 10
```

And provided a calculation for the flow:
`max - (value / total) * (max - min);`

below that, you've mentioned the following:

> I'm not 100% happy with this. I'd prefer to see the dots travel slower when flow is low, but faster when flow is high. For example if the only flow is Grid to Home, I'd like to see the dot move faster if the flow is 15kW, but slower if it's only 2kW. Right now the speed would be the same. If you have a formula you'd like to propose please submit a PR.

In my configuration, I've just removed the "max_flow_rate:10" statement, and now the dots are behaving the same as in the original energy dashboard.

While I am exporting much energy to the Grid, the dots are faster than the dots going from my solar to home.
![2022-05-13_17h20_02](https://user-images.githubusercontent.com/26391061/168315383-5531ffe1-2b2a-4161-b57a-2f3c341c8662.gif)

**Comment by ulic75** [comment]
Hello Christoph.  Github has this fancy discussion area for things that are "not an issue" 😄   All good though.

Yes the default `max_flow_rate` is 6 so removing the 10 would speed things up.  The 10 was just an arbitrary value used in the example and not intended as a recommended value.

**Reply by ChristophCaina** [reply]
but without having this max_flow_rate parameter in the card, the system is just behaving as it should (slow dot when a small amount flows, faster dot when the flow is higher.

Isn't that what you wanted to acheive, based on the description in your example?

I'm not 100% happy with this. I'd prefer to see the dots travel slower when flow is low, but faster when flow is high. For example if the only flow is Grid to Home, I'd like to see the dot move faster if the flow is 15kW, but slower if it's only 2kW. 

Here's the yaml from my card:
```
type: custom:power-flow-card
title: Live Power Distribution
entities:
  grid:
    consumption: sensor.power_grid_import
    production: sensor.power_grid_export
  solar: sensor.solaredge_modbus_ac_power
```
as you can see, I've just removed the flow_rate parameter and the dots are behaving as they do in the original / default card from the energy dashboard.
