### DISCUSSION TITLE
Wrong graphic design

### DISCUSSION THREAD

**Discussion by rubengr** [ulic75/power-flow-card#79] [Q&A] [answered]
Hi,
I'm testing power flow card with simulation sensors, but don't get the flow graphic like in readme file. Doesn't have color lines and some lines aren't visible. 
Is there an error in my configuration?
```
type: custom:power-flow-card
entities:
  battery:
    consumption: sensor.battery_out
    production: sensor.battery_in
  battery_charge: sensor.battery_percent
  grid: sensor.grid_in_out
  solar: sensor.solar_out
inverted_entities: battery, grid
```

![image](https://user-images.githubusercontent.com/6231423/174622564-17c25bc7-8fa7-44f9-b298-e16c727a7a53.png)
