### ISSUE TITLE
Card not showing energy being used by house

### ISSUE THREAD

**Issue by dorgan** [ulic75/power-flow-card#117]
Currently I have more solar power being generated than is being used by the house, but the card is showing that its all going to the grid.
![Screen Shot 2022-11-17 at 3 47 25 PM](https://user-images.githubusercontent.com/464851/202558215-8fefcfb4-b78a-4cba-acba-20599257dfe8.png)
And here is a similar card I have that shows it correctly:
![Screen Shot 2022-11-17 at 3 47 34 PM](https://user-images.githubusercontent.com/464851/202558286-5305d08a-b836-4eb0-b795-9e53d547fa3c.png)

**Comment by ulic75** [comment]
What are the values of the 3 entities shown?

In a similar test, I have
```yaml
entities:
  grid:
    consumption: input_number.grid_cons # 0
    production: input_number.grid_prod # 2000
  solar: input_number.solar # 3000
kw_decimals: 3
watt_threshold: 10000
```
The left over 1000 flows to the house.  Are perhaps some of your values negative numbers?  There is an [inverted_entities](https://github.com/ulic75/power-flow-card#inverted-entities-example) option that might be what you need.

![Screen Shot 2022-11-17 at 2 08 31 PM](https://user-images.githubusercontent.com/5641964/202560144-e4bedc88-2bd2-4994-bdb5-e5b3fbb8e0ac.png)
