### ISSUE TITLE
combine two solar system

### ISSUE THREAD

**Issue by GRV0423** [ulic75/power-flow-card#149]
is there a possibility that can be add two battery, and two solar output?

**Comment by daath** [comment]
Why not just do it yourself and use a template? E.g. 

```
- sensor:
    - name: "Plant Generation - Today"
      state: "{{ states('sensor.inverter1_energy_today') | float(0) + states('sensor.inverter2_energy_today') | float(0) }}"
      unit_of_measurement: 'kWh'
```
